@echo off
echo Eliminando .wrangler...
rmdir /s /q .wrangler 2>nul
echo Eliminando dist...
rmdir /s /q dist 2>nul
echo Eliminando node_modules...
rmdir /s /q node_modules 2>nul
echo Eliminando package-lock.json...
del package-lock.json 2>nul
echo Limpiando cache npm...
call npm cache clean --force
echo Limpieza completada
