-- Seed realistic Peruvian community missions
-- Creates 15-20 realistic missions across Lima and other regions
-- Categories: Medio ambiente, Educación, Arte & cultura, Comunidad, Salud, Tecnología

-- Insert realistic missions
INSERT INTO missions (
  title,
  description,
  district,
  region,
  category,
  xp,
  difficulty,
  date,
  participants,
  spots_left,
  distance_km,
  impact,
  coords,
  emoji,
  status,
  organizer_id
) VALUES
-- Costa - Lima Metropolitana
(
  'Reforestación del Parque Kennedy',
  'Uniremos fuerzas para plantar árboles nativos en el Parque Kennedy de Miraflores, mejorando la calidad del aire y creando espacios verdes para la comunidad.',
  'Miraflores',
  'costa',
  'Medio ambiente',
  150,
  'Andina',
  '2025-06-15',
  45,
  15,
  0,
  'Mejora calidad del aire',
  '{"lat": -12.122, "lng": -77.029}',
  '🌳',
  'active',
  (SELECT id FROM profiles LIMIT 1)
),
(
  'Taller de Reciclaje Creativo en Barranco',
  'Enseñaremos a vecinos de Barranco a transformar residuos plásticos en objetos útiles y arte, promoviendo la conciencia ambiental y la creatividad.',
  'Barranco',
  'costa',
  'Medio ambiente',
  100,
  'Suave',
  '2025-06-20',
  30,
  20,
  0,
  'Reducción de residuos',
  '{"lat": -12.148, "lng": -77.021}',
  '♻️',
  'active',
  (SELECT id FROM profiles LIMIT 1)
),
(
  'Clases de Lectura para Niños en SJL',
  'Voluntarios leerán cuentos y enseñarán lectura a niños de San Juan de Lurigancho, fomentando el amor por los libros y mejorando la educación.',
  'San Juan de Lurigancho',
  'costa',
  'Educación',
  120,
  'Suave',
  '2025-06-22',
  25,
  10,
  0,
  'Alfabetización infantil',
  '{"lat": -11.98, "lng": -77.01}',
  '📚',
  'active',
  (SELECT id FROM profiles LIMIT 1)
),
(
  'Murales Comunitarios en Villa María',
  'Artistas locales y vecinos colaborarán para pintar murales que cuenten la historia del distrito, embelleciendo espacios públicos y fortaleciendo identidad.',
  'Villa María del Triunfo',
  'costa',
  'Arte & cultura',
  130,
  'Andina',
  '2025-06-25',
  40,
  12,
  0,
  'Embellimiento urbano',
  '{"lat": -12.15, "lng": -76.95}',
  '🎨',
  'proposed',
  (SELECT id FROM profiles LIMIT 1)
),
(
  'Jornada de Salud en Comas',
  'Médicos voluntarios ofrecerán chequeos gratuitos y charlas de prevención a familias de Comas que no tienen acceso regular a servicios de salud.',
  'Comas',
  'costa',
  'Salud',
  200,
  'Andina',
  '2025-07-01',
  60,
  25,
  0,
  'Acceso a salud',
  '{"lat": -11.95, "lng": -77.05}',
  '🏥',
  'active',
  (SELECT id FROM profiles LIMIT 1)
),
(
  'Taller de Programación para Jóvenes',
  'Enseñaremos Python y desarrollo web a jóvenes de zonas vulnerables de Lima, abriendo oportunidades en el sector tecnológico.',
  'San Martín de Porres',
  'costa',
  'Tecnología',
  180,
  'Cumbre',
  '2025-07-08',
  35,
  15,
  0,
  'Inclusión digital',
  '{"lat": -11.95, "lng": -77.07}',
  '💻',
  'proposed',
  (SELECT id FROM profiles LIMIT 1)
),
(
  'Limpieza de Playas en Costa Verde',
  'Voluntarios limpiarán las playas de la Costa Verde, removiendo plásticos y residuos para proteger el ecosistema marino.',
  'Magdalena',
  'costa',
  'Medio ambiente',
  110,
  'Suave',
  '2025-07-12',
  80,
  40,
  0,
  'Protección marina',
  '{"lat": -12.08, "lng": -77.05}',
  '🌊',
  'active',
  (SELECT id FROM profiles LIMIT 1)
),
(
  'Feria de Emprendedores Locales',
  'Organizaremos una feria donde emprendedores de distritos de Lima puedan mostrar y vender sus productos, fomentando la economía local.',
  'Lima Centro',
  'costa',
  'Comunidad',
  90,
  'Suave',
  '2025-07-15',
  50,
  30,
  0,
  'Apoyo a emprendedores',
  '{"lat": -12.05, "lng": -77.03}',
  '🛍️',
  'proposed',
  (SELECT id FROM profiles LIMIT 1)
),

-- Sierra - Cusco
(
  'Restauración de Caminos Inca',
  'Trabajaremos con comunidades locales para restaurar tramos del Camino Inca cerca de Cusco, preservando patrimonio cultural y mejorando turismo sostenible.',
  'Cusco Centro',
  'sierra',
  'Arte & cultura',
  250,
  'Cumbre',
  '2025-06-18',
  35,
  10,
  0,
  'Preservación patrimonial',
  '{"lat": -13.522, "lng": -71.967}',
  '🏔️',
  'active',
  (SELECT id FROM profiles LIMIT 1)
),
(
  'Huertos Escolares en Chinchero',
  'Crearemos huertos escolares en Chinchero para enseñar a niños agricultura sostenible y nutrición, usando técnicas ancestrales.',
  'Chinchero',
  'sierra',
  'Educación',
  140,
  'Andina',
  '2025-06-28',
  25,
  15,
  0,
  'Educación alimentaria',
  '{"lat": -13.391, "lng": -72.049}',
  '🌱',
  'active',
  (SELECT id FROM profiles LIMIT 1)
),
(
  'Taller de Tejido Ancestral',
  'Maestras tejidas de Urubamba enseñarán técnicas tradicionales a jóvenes, preservando el patrimonio cultural textil de la región.',
  'Urubamba',
  'sierra',
  'Arte & cultura',
  100,
  'Suave',
  '2025-07-05',
  20,
  10,
  0,
  'Preservación cultural',
  '{"lat": -13.303, "lng": -72.116}',
  '🧵',
  'proposed',
  (SELECT id FROM profiles LIMIT 1)
),
(
  'Campaña de Vacunación en Puno',
  'Voluntarios apoyarán campaña de vacunación en comunidades rurales de Puno, asegurando acceso a inmunizaciones para niños y adultos.',
  'Puno Ciudad',
  'sierra',
  'Salud',
  220,
  'Andina',
  '2025-07-10',
  45,
  20,
  0,
  'Salud comunitaria',
  '{"lat": -15.84, "lng": -70.02}',
  '💉',
  'active',
  (SELECT id FROM profiles LIMIT 1)
),

-- Selva - Loreto
(
  'Reforestación en Iquitos',
  'Plantaremos árboles nativos en áreas deforestadas alrededor de Iquitos, ayudando a recuperar la selva y proteger la biodiversidad amazónica.',
  'Iquitos',
  'selva',
  'Medio ambiente',
  200,
  'Cumbre',
  '2025-06-30',
  30,
  15,
  0,
  'Conservación selva',
  '{"lat": -3.74, "lng": -73.25}',
  '🌴',
  'active',
  (SELECT id FROM profiles LIMIT 1)
),
(
  'Educación Ambiental para Comunidades',
  'Visitaremos comunidades ribereñas para enseñar sobre conservación del Amazonas, pesca sostenible y protección de ecosistemas.',
  'Iquitos',
  'selva',
  'Educación',
  150,
  'Andina',
  '2025-07-18',
  25,
  20,
  0,
  'Concientización ambiental',
  '{"lat": -3.75, "lng": -73.23}',
  '🦜',
  'proposed',
  (SELECT id FROM profiles LIMIT 1)
),
(
  'Apoyo a Escuelas Rurales',
  'Llevaremos libros, materiales escolares y tecnología a escuelas rurales de la selva, mejorando el acceso a educación para niños de comunidades alejadas.',
  'Iquitos',
  'selva',
  'Educación',
  180,
  'Andina',
  '2025-07-22',
  40,
  25,
  0,
  'Acceso educativo',
  '{"lat": -3.76, "lng": -73.27}',
  '🎒',
  'active',
  (SELECT id FROM profiles LIMIT 1)
),

-- Costa - La Libertad
(
  'Restauración del Centro Histórico',
  'Voluntarios ayudarán en la restauración y limpieza del centro histórico de Trujillo, preservando arquitectura colonial y promoviendo turismo cultural.',
  'Trujillo',
  'costa',
  'Arte & cultura',
  160,
  'Andina',
  '2025-07-25',
  55,
  20,
  0,
  'Patrimonio cultural',
  '{"lat": -8.115, "lng": -79.029}',
  '🏛️',
  'proposed',
  (SELECT id FROM profiles LIMIT 1)
),
(
  'Clases de Inglés para Niños',
  'Voluntarios enseñarán inglés básico a niños de Trujillo, abriendo oportunidades educativas y profesionales para el futuro.',
  'Trujillo',
  'costa',
  'Educación',
  120,
  'Suave',
  '2025-08-01',
  30,
  15,
  0,
  'Educación bilingüe',
  '{"lat": -8.12, "lng": -79.03}',
  '🗣️',
  'active',
  (SELECT id FROM profiles LIMIT 1)
);

-- Update created_at and updated_at timestamps
UPDATE missions SET created_at = NOW(), updated_at = NOW();
